# -*- coding: utf-8 -*-
"""Deploy_Integrate_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X54od62gAwr3jrv88N5Y3ezsOE9HmG6G
"""

import streamlit as st

"""Loading Both Models in Google Colab"""

import os
import shutil

# 1. 彻底打印出 ner_model 目录下的所有绝对路径，看看到底长什么样
print("=== 正在深度诊断 ner_model 目录 ===")
target_json = None
for root, dirs, files in os.walk("ner_model"):
    for file in files:
        full_p = os.path.join(root, file)
        print(f"找到文件: {full_p}")
        if file == "best_config_run_2.json":
            target_json = full_p

# 2. 如果找到了文件，直接把它的真实所在目录作为 NER_PATH
if target_json:
    NER_PATH = os.path.dirname(target_json)
    print(f"-> 成功锁定真实 NER 目录: {NER_PATH}")
else:
    print("-> 警告：在整个 ner_model 中未找到配置文件！")
    NER_PATH = "ner_model"

# 3. 严格使用绝对路径加载，避免相对路径引发的玄学报错
MODEL_CONFIG_PATH = os.path.abspath(os.path.join(NER_PATH, "best_config_run_2.json"))
MODEL_WEIGHTS_PATH = os.path.abspath(os.path.join(NER_PATH, "best_model_run_2.pt"))

print(f"最终绝对配置文件路径: {MODEL_CONFIG_PATH}")

# 4. 正式读取
with open(MODEL_CONFIG_PATH, "r", encoding="utf-8") as f:
    config_loaded = json.load(f)

print("NER config loaded successfully!")

import os
import zipfile
import shutil
import torch
import gdown
import streamlit as st
from sentence_transformers import SentenceTransformer

device = torch.device('cpu')

@st.cache_resource
def download_models():
    ner_dir = "ner_model"
    sbert_dir = "matcher_model"

    # 核心修复：如果目录存在，但关键文件缺失，说明上次解压残缺了，必须强制删掉重新下！
    if os.path.exists(ner_dir):
        if not any("best_config_run_2.json" in f for _, _, files in os.walk(ner_dir) for f in files):
            print("检测到 NER 目录残缺，正在强制清理并重新下载...")
            shutil.rmtree(ner_dir)

    if os.path.exists(sbert_dir):
        if not any("config.json" in f for _, _, files in os.walk(sbert_dir) for f in files):
            print("检测到 SBERT 目录残缺，正在强制清理并重新下载...")
            shutil.rmtree(sbert_dir)

    # 1. 下载并解压 NER 模型
    if not os.path.exists(ner_dir) or not os.listdir(ner_dir):
        os.makedirs(ner_dir, exist_ok=True)
        zip_path_ner = "ner_model.zip"
        ner_file_id = "1ftCQlp8dxP_-gNc89Sz-KvImUFjqkZpt"
        gdown.download(f"https://drive.google.com/uc?id={ner_file_id}", zip_path_ner, quiet=False)
        with zipfile.ZipFile(zip_path_ner, 'r') as zip_ref:
            zip_ref.extractall(ner_dir)
        if os.path.exists(zip_path_ner):
            os.remove(zip_path_ner)

    # 2. 下载并解压 SBERT 模型
    if not os.path.exists(sbert_dir) or not os.listdir(sbert_dir):
        os.makedirs(sbert_dir, exist_ok=True)
        zip_path_sbert = "matcher_model.zip"
        sbert_file_id = "1SWWlmouGNICG4fGCV7FjEcIESkKTCl6L"
        gdown.download(f"https://drive.google.com/uc?id={sbert_file_id}", zip_path_sbert, quiet=False)
        with zipfile.ZipFile(zip_path_sbert, 'r') as zip_ref:
            zip_ref.extractall(sbert_dir)
        if os.path.exists(zip_path_sbert):
            os.remove(zip_path_sbert)

    return ner_dir, sbert_dir

NER_MODEL_FOLDER, SBERT_MODEL_FOLDER = download_models()

# 自动寻找 NER 真实目录
def find_ner_dir(base_dir):
    for root, dirs, files in os.walk(base_dir):
        if "best_config_run_2.json" in files or "best_model_run_2.pt" in files:
            return root
    return base_dir

NER_PATH = find_ner_dir(NER_MODEL_FOLDER)
print(f"最终锁定的 NER 路径: {NER_PATH}")

MODEL_CONFIG_PATH = os.path.join(NER_PATH, "best_config_run_2.json")
MODEL_WEIGHTS_PATH = os.path.join(NER_PATH, "best_model_run_2.pt")

# 安全检查：打印绝对路径并确认它真实存在
print(f"尝试打开配置文件: {os.path.abspath(MODEL_CONFIG_PATH)}")
assert os.path.exists(MODEL_CONFIG_PATH), f"致命错误：文件在物理磁盘上找不到 -> {MODEL_CONFIG_PATH}"

with open(MODEL_CONFIG_PATH, "r", encoding="utf-8") as f:
    config_loaded = json.load(f)

print("NER config loaded successfully!")

"""Load SBERT Matcher"""

# Pass the directory path directly
print(os.listdir("matcher_model"))
sbert_model = SentenceTransformer(SBERT_PATH, device=device)
print("SBERT Matcher loaded successfully!")

"""Load NER Model (BERT-BiLSTM-CRF)"""

# 自动寻找 ner_model 文件夹里面藏有 best_model_run_2.pt 的真正目录（解决 NER 路径嵌套问题）
def find_ner_weight_path(base_dir, weight_filename="best_model_run_2.pt"):
    target_path = os.path.join(base_dir, weight_filename)
    if os.path.exists(target_path):
        return target_path
    for root, dirs, files in os.walk(base_dir):
        if weight_filename in files:
            return os.path.join(root, weight_filename)
    return target_path  # 找不到就返回默认路径抛出异常

# 动态获取正确的权重文件路径
NER_WEIGHTS_PATH = find_ner_weight_path(NER_PATH)
print(f"自动修复后的 NER 权重路径: {NER_WEIGHTS_PATH}")

# 加载 NER 权重
ner_weights = torch.load(NER_WEIGHTS_PATH, map_location=device)
print("NER weights loaded successfully!")

import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import BertTokenizer, BertModel
from torchcrf import CRF
from sentence_transformers import SentenceTransformer
import json

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

max_length = 128

# ==========================================
# 1. Install Dependencies & Setup Environment
# ==========================================

import os
import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import BertTokenizer, BertModel
from torchcrf import CRF
from sentence_transformers import SentenceTransformer

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ==========================================
# 2. Define Model Architecture Classes
# ==========================================
class SelfAttention(nn.Module):
    def __init__(self, hidden_dim):
        super().__init__()
        self.projection = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, 1, bias=False)
        )

    def forward(self, encoder_outputs, mask=None):
        energy = self.projection(encoder_outputs)
        if mask is not None:
            energy = energy.squeeze(-1).masked_fill(mask == 0, -1e9).unsqueeze(-1)
        attention_weights = F.softmax(energy, dim=1)
        return encoder_outputs * attention_weights


class BERT_BiLSTM_Attention_CRF(nn.Module):
    def __init__(self, bert_model_name, num_labels, dropout_rate=0.1, lstm_hidden_size=256, lstm_num_layers=1):
        super().__init__()
        self.bert = BertModel.from_pretrained(bert_model_name)
        self.dropout = nn.Dropout(dropout_rate)

        self.bilstm = nn.LSTM(
            input_size=self.bert.config.hidden_size,
            hidden_size=lstm_hidden_size,
            num_layers=lstm_num_layers,
            bidirectional=True,
            batch_first=True
        )

        bilstm_output_dim = lstm_hidden_size * 2
        self.attention = SelfAttention(hidden_dim=bilstm_output_dim)

        fused_dim = self.bert.config.hidden_size + bilstm_output_dim
        self.fusion_projection = nn.Linear(fused_dim, bilstm_output_dim)
        self.fusion_activation = nn.ReLU()

        self.fc = nn.Linear(bilstm_output_dim, num_labels)
        self.crf = CRF(num_labels, batch_first=True)

    def forward(self, input_ids, attention_mask, labels=None):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        sequence_output = outputs.last_hidden_state
        sequence_output_dropout = self.dropout(sequence_output)

        lstm_out, _ = self.bilstm(sequence_output_dropout)
        attended_out = self.attention(lstm_out, mask=attention_mask)

        combined_features = torch.cat([sequence_output, lstm_out + attended_out], dim=-1)

        fused_out = self.fusion_projection(combined_features)
        fused_out = self.fusion_activation(fused_out)
        fused_out = self.dropout(fused_out)

        emissions = self.fc(fused_out)

        if labels is not None:
            return -self.crf(emissions, labels, mask=attention_mask.bool(), reduction='mean')
        else:
            return self.crf.decode(emissions, mask=attention_mask.bool())

# ==========================================
# 3. Define Model File Paths & Auto-Search (Streamlit Local Paths)
# ==========================================
NER_MODEL_FOLDER = "ner_model"
SBERT_MODEL_FOLDER = "matcher_model"

# 自动寻找 NER 真实目录的函数
def find_ner_dir(base_dir):
    print(f"正在扫描 {base_dir} 下的所有文件结构：")
    for root, dirs, files in os.walk(base_dir):
        print(f"当前目录: {root}, 包含文件: {files}")
        if "best_config_run_2.json" in files or "best_model_run_2.pt" in files:
            return root
    return base_dir

# 锁定真正的 NER 和 SBERT 路径
NER_PATH = find_ner_dir(NER_MODEL_FOLDER)
print(f"最终锁定的 NER 路径: {NER_PATH}")

# 统一在这里定义好正确的最终路径，供后面直接调用
MODEL_CONFIG_PATH = os.path.join(NER_PATH, "best_config_run_2.json")
MODEL_WEIGHTS_PATH = os.path.join(NER_PATH, "best_model_run_2.pt")


# ==========================================
# 4. Load NER Model & Tokenizer
# ==========================================

# 1. Load JSON Config File
with open(MODEL_CONFIG_PATH, "r", encoding="utf-8") as f:
    config_loaded = json.load(f)

print("NER config loaded successfully!")

# loaded_label2id_crf = config_loaded['label2id_crf']
# loaded_id2label_crf = config_loaded['id2label_crf']
loaded_dropout_rate = config_loaded['dropout_rate']
loaded_lstm_hidden_size = config_loaded['lstm_hidden_size']
loaded_lstm_num_layers = config_loaded['lstm_num_layers']
loaded_max_length = max_length

# 2. Load NER Weights (强制使用 CPU 防止内存溢出)
ner_weights = torch.load(MODEL_WEIGHTS_PATH, map_location=device)
print("NER weights loaded successfully!")

loaded_label2id_crf = {
    'B-CAU': 0,
    'B-EFF': 1,
    'B-HER': 2,
    'B-PRE': 3,
    'B-SYM': 4,
    'I-CAU': 5,
    'I-EFF': 6,
    'I-HER': 7,
    'I-PRE': 8,
    'I-SYM': 9,
    'O': 10,
    'PAD': 11
}

loaded_id2label_crf = {
    0: 'B-CAU',
    1: 'B-EFF',
    2: 'B-HER',
    3: 'B-PRE',
    4: 'B-SYM',
    5: 'I-CAU',
    6: 'I-EFF',
    7: 'I-HER',
    8: 'I-PRE',
    9: 'I-SYM',
    10: 'O',
    11: 'PAD'
}

# Convert integer keys back from strings (JSON saves dict keys as strings)
loaded_id2label_crf = {int(k): v for k, v in loaded_id2label_crf.items()}

# 2. Instantiate the Model Architecture
loaded_model = BERT_BiLSTM_Attention_CRF(
    bert_model_name="bert-base-chinese",
    num_labels=len(loaded_label2id_crf),
    dropout_rate=loaded_dropout_rate,
    lstm_hidden_size=loaded_lstm_hidden_size,
    lstm_num_layers=loaded_lstm_num_layers
)

# 3. Load Model Weights (.pt file)
MODEL_WEIGHTS_PATH = os.path.join(NER_MODEL_FOLDER, "best_model_run_2.pt")
model_weights = torch.load(MODEL_WEIGHTS_PATH, map_location=device, weights_only=False)
loaded_model.load_state_dict(model_weights)

loaded_model.to(device)
loaded_model.eval()

# Load Bert Tokenizer
loaded_tokenizer = BertTokenizer.from_pretrained("bert-base-chinese")
print("✅ NER Model, Tokenizer, and Configurations loaded successfully!")

# ==========================================
# 5. Load SBERT Matcher Model
# ==========================================
sbert_model = SentenceTransformer(SBERT_PATH, device=device)
print("✅ SBERT Matcher loaded successfully!")

"""3. Test the Complete End-to-End Pipeline

newnew with herb scoring
"""

import torch

# ==========================================
# 0. Load Expanded Datasets (Herbs, Prescriptions, & Conflicting Pairs)
# ==========================================
herbs_data = [
    # --- Tonifying / Qi & Blood Tonics ---
    {"herb": "人参", "pinyin": "Ren Shen", "nature": "Warm", "flavor": "Sweet", "nature_score": 2},
    {"herb": "党参", "pinyin": "Dang Shen", "nature": "Neutral", "flavor": "Sweet", "nature_score": 0},
    {"herb": "黄芪", "pinyin": "Huang Qi", "nature": "Warm", "flavor": "Sweet", "nature_score": 2},
    {"herb": "白术", "pinyin": "Bai Zhu", "nature": "Warm", "flavor": "Sweet", "nature_score": 1},
    {"herb": "甘草", "pinyin": "Gan Cao", "nature": "Neutral", "flavor": "Sweet", "nature_score": 0},
    {"herb": "当归", "pinyin": "Dang Gui", "nature": "Warm", "flavor": "Sweet", "nature_score": 1},
    {"herb": "熟地黄", "pinyin": "Shu Di Huang", "nature": "Warm", "flavor": "Sweet", "nature_score": 1},
    {"herb": "白芍", "pinyin": "Bai Shao", "nature": "Cool", "flavor": "Bitter", "nature_score": -1},
    {"herb": "阿胶", "pinyin": "E Jiao", "nature": "Neutral", "flavor": "Sweet", "nature_score": 0},
    {"herb": "枸杞子", "pinyin": "Gou Qi Zi", "nature": "Neutral", "flavor": "Sweet", "nature_score": 0},

    # --- Heat-Clearing / Fire-Purging ---
    {"herb": "黄连", "pinyin": "Huang Lian", "nature": "Cold", "flavor": "Bitter", "nature_score": -2},
    {"herb": "黄芩", "pinyin": "Huang Qin", "nature": "Cold", "flavor": "Bitter", "nature_score": -2},
    {"herb": "黄柏", "pinyin": "Huang Bai", "nature": "Cold", "flavor": "Bitter", "nature_score": -2},
    {"herb": "金银花", "pinyin": "Jin Yin Hua", "nature": "Cold", "flavor": "Sweet", "nature_score": -2},
    {"herb": "连翘", "pinyin": "Lian Qiao", "nature": "Cool", "flavor": "Bitter", "nature_score": -1},
    {"herb": "大青叶", "pinyin": "Da Qing Ye", "nature": "Cold", "flavor": "Bitter", "nature_score": -2},
    {"herb": "板蓝根", "pinyin": "Ban Lan Gen", "nature": "Cold", "flavor": "Bitter", "nature_score": -2},
    {"herb": "石膏", "pinyin": "Shi Gao", "nature": "Cold", "flavor": "Sweet", "nature_score": -3},
    {"herb": "知母", "pinyin": "Zhi Mu", "nature": "Cold", "flavor": "Bitter", "nature_score": -2},
    {"herb": "芦根", "pinyin": "Lu Gen", "nature": "Cold", "flavor": "Sweet", "nature_score": -2},

    # --- Exterior-Releasing (Wind-Cold / Wind-Heat) ---
    {"herb": "麻黄", "pinyin": "Ma Huang", "nature": "Warm", "flavor": "Pungent", "nature_score": 2},
    {"herb": "桂枝", "pinyin": "Gui Zhi", "nature": "Warm", "flavor": "Pungent", "nature_score": 2},
    {"herb": "生姜", "pinyin": "Sheng Jiang", "nature": "Warm", "flavor": "Pungent", "nature_score": 2},
    {"herb": "紫苏叶", "pinyin": "Zi Su Ye", "nature": "Warm", "flavor": "Pungent", "nature_score": 2},
    {"herb": "防风", "pinyin": "Fang Feng", "nature": "Warm", "flavor": "Pungent", "nature_score": 1},
    {"herb": "薄荷", "pinyin": "Bo He", "nature": "Cool", "flavor": "Pungent", "nature_score": -1},
    {"herb": "桑叶", "pinyin": "Sang Ye", "nature": "Cool", "flavor": "Bitter", "nature_score": -1},
    {"herb": "菊花", "pinyin": "Ju Hua", "nature": "Cool", "flavor": "Sweet", "nature_score": -1},
    {"herb": "柴胡", "pinyin": "Chai Hu", "nature": "Cool", "flavor": "Bitter", "nature_score": -1},
    {"herb": "葛根", "pinyin": "Ge Gen", "nature": "Cool", "flavor": "Sweet", "nature_score": -1},

    # --- Warming Interior / Cold-Expelling ---
    {"herb": "附子", "pinyin": "Fu Zi", "nature": "Hot", "flavor": "Pungent", "nature_score": 3},
    {"herb": "干姜", "pinyin": "Gan Jiang", "nature": "Hot", "flavor": "Pungent", "nature_score": 3},
    {"herb": "肉桂", "pinyin": "Rou Gui", "nature": "Hot", "flavor": "Pungent", "nature_score": 3},
    {"herb": "吴茱萸", "pinyin": "Wu Zhu Yu", "nature": "Hot", "flavor": "Pungent", "nature_score": 3},
    {"herb": "细辛", "pinyin": "Xi Xin", "nature": "Warm", "flavor": "Pungent", "nature_score": 2},

    # --- Phlegm-Resolving & Damp-Draining ---
    {"herb": "半夏", "pinyin": "Ban Xia", "nature": "Warm", "flavor": "Pungent", "nature_score": 1},
    {"herb": "陈皮", "pinyin": "Chen Pi", "nature": "Warm", "flavor": "Pungent", "nature_score": 1},
    {"herb": "茯苓", "pinyin": "Fu Ling", "nature": "Neutral", "flavor": "Sweet", "nature_score": 0},
    {"herb": "苍术", "pinyin": "Cang Zhu", "nature": "Warm", "flavor": "Pungent", "nature_score": 2},
    {"herb": "厚朴", "pinyin": "Hou Po", "nature": "Warm", "flavor": "Pungent", "nature_score": 2},
    {"herb": "泽泻", "pinyin": "Ze Xie", "nature": "Cold", "flavor": "Sweet", "nature_score": -2},
    {"herb": "薏苡仁", "pinyin": "Yi Yi Ren", "nature": "Cool", "flavor": "Sweet", "nature_score": -1},

    # --- Purgatives & Laxatives ---
    {"herb": "大黄", "pinyin": "Da Huang", "nature": "Cold", "flavor": "Bitter", "nature_score": -3},
    {"herb": "芒硝", "pinyin": "Mang Xiao", "nature": "Cold", "flavor": "Salty", "nature_score": -3},
    {"herb": "火麻仁", "pinyin": "Huo Ma Ren", "nature": "Neutral", "flavor": "Sweet", "nature_score": 0},

    # --- Relieving Food Stagnation & Blood-Moving ---
    {"herb": "山楂", "pinyin": "Shan Zha", "nature": "Warm", "flavor": "Sour", "nature_score": 1},
    {"herb": "神曲", "pinyin": "Shen Qu", "nature": "Warm", "flavor": "Sweet", "nature_score": 1},
    {"herb": "川芎", "pinyin": "Chuan Xiong", "nature": "Warm", "flavor": "Pungent", "nature_score": 2},
    {"herb": "丹参", "pinyin": "Dan Shen", "nature": "Cool", "flavor": "Bitter", "nature_score": -1},
    {"herb": "桃仁", "pinyin": "Tao Ren", "nature": "Neutral", "flavor": "Bitter", "nature_score": 0},
    {"herb": "红花", "pinyin": "Hong Hua", "nature": "Warm", "flavor": "Pungent", "nature_score": 2}
]

conflicts_data = [
    {"herb_a": "甘草", "herb_b": "甘遂"},
    {"herb_a": "甘草", "herb_b": "大戟"},
    {"herb_a": "甘草", "herb_b": "海藻"},
    {"herb_a": "甘草", "herb_b": "芫花"},
    {"herb_a": "乌头", "herb_b": "半夏"},
    {"herb_a": "乌头", "herb_b": "瓜蒌"},
    {"herb_a": "乌头", "herb_b": "贝母"},
    {"herb_a": "乌头", "herb_b": "白蔹"},
    {"herb_a": "乌头", "herb_b": "白及"},
    {"herb_a": "藜芦", "herb_b": "人参"},
    {"herb_a": "藜芦", "herb_b": "沙参"},
    {"herb_a": "藜芦", "herb_b": "丹参"},
    {"herb_a": "藜芦", "herb_b": "玄参"},
    {"herb_a": "藜芦", "herb_b": "苦参"},
    {"herb_a": "藜芦", "herb_b": "细辛"},
    {"herb_a": "藜芦", "herb_b": "芍药"}
]

conflicts_data = [
    {"herb_a": "甘草", "herb_b": "甘遂"},
    {"herb_a": "乌头", "herb_b": "半夏"}
]

# Combine both herbs and prescriptions into a unified candidate pool
formatted_candidates = [
    f"[单味药] {item['herb']} ({item['pinyin']}) - 性味: {item['nature']} {item['flavor']}"
    for item in herbs_data
] + [
    f"[经典方剂] {item['name']} - 功效主治: {item['indication']} (分类: {item['category']})"
    for item in prescriptions_data
]


# ==========================================
# 1. Define Entity Extraction Function (NER)
# ==========================================
def extract_entities(text, model, tokenizer, id2label, max_len=64):
    model.eval()
    inputs = tokenizer(
        text,
        max_length=max_len,
        padding='max_length',
        truncation=True,
        return_tensors="pt"
    )

    input_ids = inputs['input_ids'].to(device)
    attention_mask = inputs['attention_mask'].to(device)

    with torch.no_grad():
        predicted_tag_ids = model(input_ids, attention_mask=attention_mask)[0]

    tokens = tokenizer.convert_ids_to_tokens(input_ids[0])
    extracted_entities = []
    current_entity = ""
    current_type = None

    for token, tag_id in zip(tokens[1:], predicted_tag_ids[1:]):
        if token in ["[SEP]", "[PAD]"]:
            break
        label = id2label.get(tag_id, "O")
        if label.startswith("B-"):
            if current_entity:
                extracted_entities.append((current_entity, current_type))
            current_entity = token.replace("##", "")
            current_type = label.split("-")[1]
        elif label.startswith("I-") and current_entity:
            current_entity += token.replace("##", "")
        else:
            if current_entity:
                extracted_entities.append((current_entity, current_type))
                current_entity = ""
                current_type = None

    if current_entity:
        extracted_entities.append((current_entity, current_type))
    return extracted_entities


# ==========================================
# 2. Safety Checker Function (Eighteen Antagonists)
# ==========================================
def check_herb_conflicts(top_results, conflicts):
    warnings = []
    combined_text = " ".join([res for res, score in top_results])

    for c in conflicts:
        a, b = c['herb_a'], c['herb_b']
        if a in combined_text and b in combined_text:
            warnings.append(f"🚨 安全警告: 推荐结果中存在十八反禁忌组合 [{a}] 与 [{b}]！")
    return warnings


# ==========================================
# 3. Define Improved Pipeline with Query Expansion
# ==========================================

def predict_tcm_pipeline_improved(input_text, candidate_pool=formatted_candidates, top_k=5):
    print(f"\n📥 Input Patient Text: '{input_text}'")
    print("-" * 50)

    # ============================================================
    # Step 1: Extract Entities using NER
    # ============================================================
    entities = extract_entities(
        input_text,
        loaded_model,
        loaded_tokenizer,
        loaded_id2label_crf,
        max_len=loaded_max_length
    )

    print("🏷️ Extracted Entities (NER):")

    if not entities:
        print("  ⚠️ No entities detected!")
        return

    for entity, entity_type in entities:
        print(f"  • [{entity_type}] : {entity}")


    # ============================================================
    # Step 1.1: Separate SYM and HER entities
    # ============================================================
    symptoms = [
        entity for entity, etype in entities
        if etype in ["SYM", "B-SYM", "I-SYM"]
    ]

    herbs = [
        entity for entity, etype in entities
        if etype in ["HER", "B-HER", "I-HER"]
    ]

    print(f"\n🩺 Symptoms Used for Matching: {symptoms}")
    print(f"🌿 Herbs Mentioned by Patient: {herbs}")


    # ============================================================
    # Step 1.2: Detect context/role of mentioned herbs
    # ============================================================
    def detect_herb_context(text, herb):
        """
        Determine how the patient mentions the herb.
        This is a lightweight rule-based contextual layer.
        """

        idx = text.find(herb)

        if idx == -1:
            return "MENTIONED"

        # Take surrounding context of the herb
        context_start = max(0, idx - 20)
        context_end = min(len(text), idx + len(herb) + 20)
        context = text[context_start:context_end]

        # Patient is asking whether the herb is effective/suitable
        queried_words = [
            "有效吗",
            "有用吗",
            "可以吗",
            "能缓解吗",
            "能治疗吗",
            "适合吗",
            "能不能吃",
            "能不能用",
            "是否可以",
            "有没有用"
        ]

        # Patient has already taken/used the herb
        taken_words = [
            "已经吃",
            "已经服用",
            "已经用了",
            "正在吃",
            "正在服用",
            "正在用",
            "吃了",
            "服用了",
            "用了",
            "喝了"
        ]

        # Patient is requesting/recommending the herb for themselves
        requested_words = [
            "推荐",
            "应该吃",
            "应该用",
            "想吃",
            "想用",
            "可以用",
            "可以吃"
        ]

        if any(word in context for word in queried_words):
            return "QUERIED"

        if any(word in context for word in taken_words):
            return "TAKEN"

        if any(word in context for word in requested_words):
            return "REQUESTED"

        return "MENTIONED"


    herb_roles = {
        herb: detect_herb_context(input_text, herb)
        for herb in herbs
    }

    if herb_roles:
        print("\n🔎 Herb Context Analysis:")
        for herb, role in herb_roles.items():
            print(f"  • {herb} → {role}")


    # ============================================================
    # Step 1.3: Construct SBERT query using SYM ONLY
    # ============================================================
    if symptoms:
        symptom_keywords = "、".join(symptoms)

        expanded_query = (
            f"患者主诉症状表现为：{symptom_keywords}，"
            f"应选用何种中药或经典方剂进行调理治疗？"
        )
    else:
        # Fallback if no symptoms were detected
        expanded_query = input_text

    print(
        f"\n🔍 Expanded Query Sent to SBERT Matcher: "
        f"'{expanded_query}'"
    )


    # ============================================================
    # Step 2: SBERT Similarity Matching
    # ============================================================
    query_embedding = sbert_model.encode(
        expanded_query,
        convert_to_tensor=True
    )

    candidate_embeddings = sbert_model.encode(
        candidate_pool,
        convert_to_tensor=True
    )

    similarity_scores = torch.nn.functional.cosine_similarity(
        query_embedding,
        candidate_embeddings
    )


    # ============================================================
    # Step 2.1: Herb Contextual Weighting
    # ============================================================
    #
    # Important:
    # HER is NOT added into the SBERT query.
    # Instead, it is used as a separate contextual signal.
    #
    # Small bonus values are used so that herb context does not
    # overpower symptom-based semantic matching.
    # ============================================================

    HERB_BONUS = {
        "QUERIED": 0.02,
        "REQUESTED": 0.02,
        "TAKEN": 0.00,
        "MENTIONED": 0.00
    }

    adjusted_results = []

    for item, similarity in zip(
        candidate_pool,
        similarity_scores.tolist()
    ):

        final_score = similarity
        herb_adjustment = 0.0
        matched_herb = None
        matched_role = None

        # Check whether candidate herb was explicitly mentioned
        # by the patient.
        for herb, role in herb_roles.items():

            # Candidate may contain additional information,
            # so use substring matching.
            if herb in item:

                matched_herb = herb
                matched_role = role

                herb_adjustment = HERB_BONUS.get(role, 0.0)
                final_score += herb_adjustment

                break

        adjusted_results.append({
            "item": item,
            "sbert_score": similarity,
            "herb_adjustment": herb_adjustment,
            "final_score": final_score,
            "matched_herb": matched_herb,
            "herb_role": matched_role
        })


    # ============================================================
    # Step 2.2: Sort using FINAL SCORE
    # ============================================================
    adjusted_results = sorted(
        adjusted_results,
        key=lambda x: x["final_score"],
        reverse=True
    )

    top_results = adjusted_results[:top_k]


    # ============================================================
    # Step 3: Display Final Recommendations
    # ============================================================
    print(
        f"\n🌿 Top {top_k} Recommendation Results "
        f"(Herbs & Prescriptions):"
    )

    for rank, result in enumerate(top_results, start=1):

        item = result["item"]
        sbert_score = result["sbert_score"]
        herb_adjustment = result["herb_adjustment"]
        final_score = result["final_score"]

        print(
            f"  {rank}. {item} "
            f"(SBERT: {sbert_score:.4f}, "
            f"Herb Adjustment: {herb_adjustment:+.4f}, "
            f"Final Score: {final_score:.4f})"
        )

        if result["matched_herb"]:
            print(
                f"      ↳ Patient-mentioned herb: "
                f"{result['matched_herb']} "
                f"({result['herb_role']})"
            )


    # ============================================================
    # Step 4: Check Conflict Rules
    # ============================================================

    # Convert results back to the original
    # (item, score) format required by check_herb_conflicts()
    top_results_for_conflict = [
        (result["item"], result["final_score"])
        for result in top_results
    ]

    conflicts_found = check_herb_conflicts(
        top_results_for_conflict,
        conflicts_data
    )

    if conflicts_found:
        print("\n⚠️ 禁忌校验系统检测结果：")

        for warning in conflicts_found:
            print(f"  {warning}")

    else:
        print(
            "\n✅ 十八反禁忌校验通过："
            "推荐结果无配伍冲突。"
        )

"""Result"""

